name: 'Build Binary Ubuntu'
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  BUILD_RELEASE:
    runs-on: ubuntu-latest
    container:
      image: 'jasonyangee/stm32_ubuntu:latest'
    steps:
    - uses: actions/checkout@v3
    - name: BUILD
      run: build.sh

    - name: Upload Binary .elf
      uses: actions/upload-artifact@v2
      with:
        name: L432KC-TEMPLATE.elf
        path: $GIT_WORKSPACE/build/L432KC.elf

    - name: Upload Binary .bin
      uses: actions/upload-artifact@v2
      with:
        name: L432KC-TEMPLATE.bin
        path: $GIT_WORKSPACE/build/L432KC.bin