on:
  push:
    branches:
      - "main"

jobs:
  run_image:
    runs-on: ubuntu-latest
    container:
      image: jasonyangee/stm32_alpine:latest
      options: --entrypoint bin/bash
      volumes:
      - /.:/home/
    steps:
    - name: init
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE:PATH="/home/cmake/gcc-arm-none-eabi.cmake" "-B /home/build/Debug/" -G Ninja
    
    - name: build
      run: cmake --build /home/build/Debug/ -j 10
